name: extended_text_field
description: Extended official text field to build special text like inline image, @somebody, custom background etc quickly.It also support to build custom seleciton toolbar and handles.
version: 16.0.2
repository: https://github.com/fluttercandies/extended_text_field
issue_tracker: https://github.com/fluttercandies/extended_text_field/issues
topics:
  - extended-text-field
  - rich-text

environment:
  sdk: '>=3.5.0 <4.0.0'
  flutter: ">=3.24.0"
dependencies:

  extended_text_library: ^12.0.0
  # extended_text_library:  
  #   version: ^11.0.0-dev.1
  #   hosted: "https://pub.dev"
  flutter:  
    sdk: flutter
dev_dependencies:
  flutter_test:
    sdk: flutter

dependency_overrides:
  #extended_text_library:
    # git: 
    #   url: https://github.com/fluttercandies/extended_text_library.git
    #   ref: refactor
    #path: ../extended_text_library
# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # To add assets to your package, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.io/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.io/custom-fonts/#from-packages
