// GENERATED CODE - DO NOT MODIFY MANUALLY
// **************************************************************************
// Auto generated by https://github.com/fluttercandies/ff_annotation_route
// **************************************************************************
// fast mode: true
// version: 10.0.6
// **************************************************************************
// ignore_for_file: prefer_const_literals_to_create_immutables,unused_local_variable,unused_import,unnecessary_import,unused_shown_name,implementation_imports,duplicate_import
const List<String> routeNames = <String>[
  'fluttercandies://CustomToolBar',
  'fluttercandies://NoKeyboard',
  'fluttercandies://TextDemo',
  'fluttercandies://WidgetSpanDemo',
  'fluttercandies://demogrouppage',
  'fluttercandies://mainpage',
];

class Routes {
  const Routes._();

  /// 'custom selection toolbar and handles for text field'
  ///
  /// [name] : 'fluttercandies://CustomToolBar'
  ///
  /// [routeName] : 'custom toolbar'
  ///
  /// [description] : 'custom selection toolbar and handles for text field'
  ///
  /// [exts] : {'group': 'Simple', 'order': 0}
  static const String fluttercandiesCustomToolBar =
      'fluttercandies://CustomToolBar';

  /// 'show how to ignore system keyboard and show custom keyboard'
  ///
  /// [name] : 'fluttercandies://NoKeyboard'
  ///
  /// [routeName] : 'no system Keyboard'
  ///
  /// [description] : 'show how to ignore system keyboard and show custom keyboard'
  ///
  /// [constructors] :
  ///
  /// NoSystemKeyboardDemo : [Key? key]
  ///
  /// [exts] : {'group': 'Simple', 'order': 2}
  static const String fluttercandiesNoKeyboard = 'fluttercandies://NoKeyboard';

  /// 'build special text and inline image in text field'
  ///
  /// [name] : 'fluttercandies://TextDemo'
  ///
  /// [routeName] : 'text'
  ///
  /// [description] : 'build special text and inline image in text field'
  ///
  /// [exts] : {'group': 'Complex', 'order': 0}
  static const String fluttercandiesTextDemo = 'fluttercandies://TextDemo';

  /// 'mailbox demo with widgetSpan'
  ///
  /// [name] : 'fluttercandies://WidgetSpanDemo'
  ///
  /// [routeName] : 'widget span'
  ///
  /// [description] : 'mailbox demo with widgetSpan'
  ///
  /// [exts] : {'group': 'Simple', 'order': 1}
  static const String fluttercandiesWidgetSpanDemo =
      'fluttercandies://WidgetSpanDemo';

  /// 'DemoGroupPage'
  ///
  /// [name] : 'fluttercandies://demogrouppage'
  ///
  /// [routeName] : 'DemoGroupPage'
  ///
  /// [constructors] :
  ///
  /// DemoGroupPage : [MapEntry<String?, List<DemoRouteResult>>(required) keyValue]
  static const String fluttercandiesDemogrouppage =
      'fluttercandies://demogrouppage';

  /// 'MainPage'
  ///
  /// [name] : 'fluttercandies://mainpage'
  ///
  /// [routeName] : 'MainPage'
  ///
  /// [constructors] :
  ///
  /// MainPage : []
  static const String fluttercandiesMainpage = 'fluttercandies://mainpage';
}
