// GENERATED CODE - DO NOT MODIFY MANUALLY
// **************************************************************************
// Auto generated by https://github.com/fluttercandies/ff_annotation_route
// **************************************************************************
const List<String> routeNames = <String>[
  'fluttercandies://CustomToolBar',
  'fluttercandies://TextDemo',
  'fluttercandies://WidgetSpanDemo',
  'fluttercandies://mainpage',
  'fluttercandies://picswiper'
];

class Routes {
  const Routes._();

  /// "custom selection toolbar and handles for text field"
  ///
  /// [name] : fluttercandies://CustomToolBar
  ///
  /// [routeName] : custom toolbar
  ///
  /// [description] : "custom selection toolbar and handles for text field"
  static const String fluttercandiesCustomToolBar =
      'fluttercandies://CustomToolBar';

  /// "build special text and inline image in text field"
  ///
  /// [name] : fluttercandies://TextDemo
  ///
  /// [routeName] : text
  ///
  /// [description] : "build special text and inline image in text field"
  static const String fluttercandiesTextDemo = 'fluttercandies://TextDemo';

  /// "mailbox demo with widgetSpan"
  ///
  /// [name] : fluttercandies://WidgetSpanDemo
  ///
  /// [routeName] : widget span
  ///
  /// [description] : "mailbox demo with widgetSpan"
  static const String fluttercandiesWidgetSpanDemo =
      'fluttercandies://WidgetSpanDemo';

  /// MainPage
  ///
  /// [name] : fluttercandies://mainpage
  ///
  /// [routeName] : MainPage
  static const String fluttercandiesMainpage = 'fluttercandies://mainpage';

  /// PicSwiper
  ///
  /// [name] : fluttercandies://picswiper
  ///
  /// [routeName] : PicSwiper
  ///
  /// [arguments] : [index, pics, tuChongItem]
  ///
  /// [showStatusBar] : false
  ///
  /// [pageRouteType] : PageRouteType.transparent
  static const String fluttercandiesPicswiper = 'fluttercandies://picswiper';
}
