// GENERATED CODE - DO NOT MODIFY MANUALLY
// **************************************************************************
// Auto generated by https://github.com/fluttercandies/ff_annotation_route
// **************************************************************************
// ignore_for_file: prefer_const_literals_to_create_immutables,unused_local_variable,unused_import
const List<String> routeNames = <String>[
  'fluttercandies://CustomToolBar',
  'fluttercandies://TextDemo',
  'fluttercandies://WidgetSpanDemo',
  'fluttercandies://demogrouppage',
  'fluttercandies://mainpage',
];

class Routes {
  const Routes._();

  /// 'custom selection toolbar and handles for text field'
  ///
  /// [name] : 'fluttercandies://CustomToolBar'
  ///
  /// [routeName] : 'custom toolbar'
  ///
  /// [description] : 'custom selection toolbar and handles for text field'
  ///
  /// [exts] : {group: Simple, order: 0}
  static const String fluttercandiesCustomToolBar =
      'fluttercandies://CustomToolBar';

  /// 'build special text and inline image in text field'
  ///
  /// [name] : 'fluttercandies://TextDemo'
  ///
  /// [routeName] : 'text'
  ///
  /// [description] : 'build special text and inline image in text field'
  ///
  /// [exts] : {group: Complex, order: 0}
  static const String fluttercandiesTextDemo = 'fluttercandies://TextDemo';

  /// 'mailbox demo with widgetSpan'
  ///
  /// [name] : 'fluttercandies://WidgetSpanDemo'
  ///
  /// [routeName] : 'widget span'
  ///
  /// [description] : 'mailbox demo with widgetSpan'
  ///
  /// [exts] : {group: Simple, order: 1}
  static const String fluttercandiesWidgetSpanDemo =
      'fluttercandies://WidgetSpanDemo';

  /// 'DemoGroupPage'
  ///
  /// [name] : 'fluttercandies://demogrouppage'
  ///
  /// [routeName] : 'DemoGroupPage'
  ///
  /// [constructors] :
  ///
  /// DemoGroupPage : [MapEntry<String?, List<DemoRouteResult>>(required) keyValue]
  static const String fluttercandiesDemogrouppage =
      'fluttercandies://demogrouppage';

  /// 'MainPage'
  ///
  /// [name] : 'fluttercandies://mainpage'
  ///
  /// [routeName] : 'MainPage'
  ///
  /// [constructors] :
  ///
  /// MainPage : []
  static const String fluttercandiesMainpage = 'fluttercandies://mainpage';
}
